import Head from 'next/head'
import Image from "next/image";

import {
    BsFillMoonStarsFill
} from "react-icons/bs";
import {
    AiFillTwitterCircle,
    AiFillLinkedin,
    AiFillYoutube,
} from "react-icons/ai";

import deved from '../public/deved.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between">
                <h1 className="text-xl font-burtons">developedbyat</h1>
                <ul className="flex items-center">
                    <li>
                        <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
                    </li>
                    <li>
                        <a href="#" className="bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">Resume</a>
                    </li>
                </ul>
            </nav>
            <div className="text-center p-10">
                <h2 className="text-5xl py-2 text-teal-600 font-medium">Sungur Atay</h2>
                <h3 className="text-2xl py-2">Developer and designer</h3>
                <p className="text-md py-5 leading-8 text-gray-800">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid at aut, earum eius eos eum ex incidunt ipsum iure modi molestias natus placeat quae ratione repellendus rerum similique veniam vitae.
                </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                <AiFillTwitterCircle />
                <AiFillLinkedin />
                <AiFillYoutube />
            </div>
            <div className="mx-auto relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 overflow-hidden mt-20">
                <Image src={deved} alt="developer" layout="fill" objectFit="cover" />
            </div>
        </section>
        <section className="mt-10">
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-80">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut est minima nihil officia. Aperiam deleniti distinctio fugit hic incidunt iste labore nemo nobis praesentium quaerat? Facilis laboriosam officia officiis quo!
            </p>
            <p className="text-md py-2 leading-8 text-gray-80">
                <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut est minima nihil officia.</span>
            </p>
            <div>
                <div className="flex flex-col items-center shadow-lg p-10 rounded-xl my-10">
                    <Image src={design} width={100} height={100} />
                    <h3 className="text-lg font-medium pt-8 pb-2">
                        Beautiful Designs
                    </h3>
                    <p className="py-2">
                        Creating elegant designs suited for your needs following core design theory.
                    </p>
                    <h4 className="py-4 text-teal-600">Design tools I use</h4>
                    <p className="text-gray-800 py-1">Photoshop</p>
                    <p className="text-gray-800 py-1">Illustrator</p>
                    <p className="text-gray-800 py-1">Figma</p>
                </div>
            </div>
        </section>
      </main>
    </div>
  )
}
