import Head from 'next/head'
import Hero from '../components/Hero';
import Service from '../components/Service';
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
          <Hero />
          <section className="mt-10">
              <h3 className="text-3xl py-1">Services I offer</h3>
              <p className="text-md py-2 leading-8 text-gray-80">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut est minima nihil officia. Aperiam deleniti distinctio fugit hic incidunt iste labore nemo nobis praesentium quaerat? Facilis laboriosam officia officiis quo!
              </p>
              <p className="text-md py-2 leading-8 text-gray-80">
                  <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut est minima nihil officia.</span>
              </p>
              <div>
                  <Service img={design} />
                  <Service img={code} />
                  <Service img={consulting} />
              </div>
          </section>

      </main>
    </div>
  )
}
