import Head from 'next/head'
import Hero from '../components/Hero';
import Service from '../components/Service';
import Portfolio from '../components/Portfolio';

import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'

import { useState } from 'react';

export default function Home() {
    const [darkMode, setDarkMode] = useState(false)

    const toggleDarkMode = () => {
        setDarkMode(!darkMode)
    }

    return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
          <Hero toggleDarkMode={toggleDarkMode}/>
          <section className="mt-10">
              <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                  Since the beginning of my journey as a freelance designer and
                  developer, I have done remote work for
                  <span className="text-teal-500"> agencies </span>
                  consulted for <span className="text-teal-500">startups </span>
                  and collaborated with talanted people to create digital products
                  for both business and consumer use.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                  I offer from a wide range of services, including brand design,
                  programming and teaching.
              </p>
              <div className="lg:flex gap-10">
                  <Service img={design} />
                  <Service img={code} />
                  <Service img={consulting} />
              </div>
          </section>
          <Portfolio />
      </main>
    </div>
  )
}
